import type { Metadata } from "next";
import localFont from "next/font/local";
import {Quicksand} from "next/font/google"
import "./globals.css";
import { Poppins } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


const geistQuickSand = Quicksand({
  weight:["300","400","500","600" , "700"],
  display:"swap",
  variable:"--font-quicksand",
  subsets:['latin']
})


const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});


















export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistQuickSand.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
