import type { Metadata } from "next";
import localFont from "next/font/local";
import { Cherry_Swash, Comic_Neue, Quicksand } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Chewy, Comfortaa } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const geistQuickSand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const chew = Chewy({
  subsets: ["latin"],
  variable: "--font-chew",
  display: "swap",
  weight: ["400"],
});

const comic = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comic",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${chew.variable}  ${comic.variable}  antialiased overflow-x-hidden`}
      >
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
